"""initial schema

Revision ID: 8248c8d94400
Revises: 
Create Date: 2026-03-10 15:06:56.277339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8248c8d94400'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pesel', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('imie', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nazwisko', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('data_urodzenia', sa.Date(), nullable=False),
    sa.Column('plec', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('telefon', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('koresp_ulica', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('koresp_nr_domu', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('koresp_nr_mieszkania', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('koresp_miasto', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('koresp_kod_pocztowy', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.CheckConstraint("plec IN ('M', 'K')", name='ck_citizens_plec'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizens_pesel'), 'citizens', ['pesel'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('typ_operacji', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('opis', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('obywatel_id', sa.Integer(), nullable=True),
    sa.Column('dane_przed', sa.JSON(), nullable=True),
    sa.Column('dane_po', sa.JSON(), nullable=True),
    sa.CheckConstraint("typ_operacji IN ('CREATE', 'UPDATE', 'DELETE', 'VIEW')", name='ck_audit_log_typ_operacji'),
    sa.ForeignKeyConstraint(['obywatel_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obywatel_id', sa.Integer(), nullable=False),
    sa.Column('typ', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('seria', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('numer', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('data_wydania', sa.Date(), nullable=False),
    sa.Column('data_waznosci', sa.Date(), nullable=False),
    sa.Column('organ_wydajacy', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("typ IN ('dowod', 'paszport')", name='ck_identity_documents_typ'),
    sa.ForeignKeyConstraint(['obywatel_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obywatel_id', sa.Integer(), nullable=False),
    sa.Column('ulica', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('nr_domu', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nr_mieszkania', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('miasto', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('kod_pocztowy', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('typ_zameldowania', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('data_zameldowania', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("typ_zameldowania IN ('stale', 'tymczasowe')", name='ck_registration_entries_typ'),
    sa.ForeignKeyConstraint(['obywatel_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_entries')
    op.drop_table('identity_documents')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_citizens_pesel'), table_name='citizens')
    op.drop_table('citizens')
    # ### end Alembic commands ###
